#Set up Job
name: Terraform-plan
on:
  pull_request:
    branches:
      - main


jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #Setup Terraform
      - name: Setup Terraform
        run: terraform init
        #Terraform Init

      - name: Terraform Format
        run: terraform fmt -check -recursive


        #Terraform Validate
      - name: Terraform Validate
        run: terraform  validate
#Post Checkout

#Complete job